version: "3.8"

services:
  livequiz:
    image: ghcr.io/ineiti/livequiz2:latest
    build: .
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - STATIC_PAGE=./frontend
      - NOMADS_DB=/root/db
    volumes:
      - ./db:/root/db
    ports:
      - 8000:8000
#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.livequiz.rule=Host(`livequiz.fledg.re`)"
#       - "traefik.http.routers.livequiz.entrypoints=websecure"
#       - "traefik.http.routers.livequiz.tls.certresolver=myresolver"
#       - "traefik.http.services.livequiz.loadbalancer.server.port=8000"
#       - "com.centurylinklabs.watchtower.enable=true"
#       - "traefik.http.routers.livequiz.service=livequiz"
#     networks:
#       - traefik

# networks:
#   traefik:
#     external:
#       name: traefik_traefik
